### ISSUE TITLE
homeにおいて自分に閲覧権限のある全てのコメントを横断して時系列に表示。そしてそれはwebsocketライブラリを使ってリアルタイム更新

### ISSUE THREAD

**Issue by pandeiro245** [timecard/timecard-rails#173]

**Comment by pandeiro245** [comment]
こういうのがあるのね
https://github.com/websocket-rails/websocket-rails

**Comment by kmiyake** [comment]
Gemの使い方を調べる。

**Comment by kmiyake** [comment]
websocket-railsを試してみるためインストールする。

**Comment by kmiyake** [comment]
トップページにコメントを表示する。

**Comment by kmiyake** [comment]
public_activityを導入する。

**Comment by kmiyake** [comment]
websocket-rails面白い。

**Comment by kmiyake** [comment]
開発環境でwebsocketを使用する場合はlocalhostで立ち上げる必要あり。powはwebsocketをサポートしていない。
