### ISSUE TITLE
Issueのupdateでエラー

### ISSUE THREAD

**Issue by kmiyake** [timecard/timecard-rails#18]

**Comment by kmiyake** [comment]
元々Github連携されていないIssueを更新しようとするとエラーとなる。

**Comment by pandeiro245** [comment]
@kmiyake お手数おかけします…。対応ありがとうございます。

**Comment by kmiyake** [comment]
@pandeiro245 issueに対してgithub連携の有無を確認するチェックを追加しました。

**Comment by kmiyake** [comment]
@pandeiro245 PRしましたので確認をお願いします。

Issueのupdateでエラー by kmiyake · Pull Request #19 · mindia/timecard-rails
https://github.com/mindia/timecard-rails/pull/19

**Comment by pandeiro245** [comment]
@kmiyake さんご対応ありがとうございます。
mergeして
http://timecard-rails.herokuapp.com/
に反映しました。
if @issue.project.github && @issue.github.ni?
にマッチした時は
その場で@issue.add_github するような仕様をRuffnoteで提案したいと思います。
