### ISSUE TITLE
「WorkLog」モデルの名前を「Workload」に変更

### ISSUE THREAD

**Issue by pandeiro245** [timecard/timecard-rails#21]
work_logs_controllerは不要？
https://ruffnote.com/timecard/timecard/2338
https://ruffnote.com/timecard/timecard/3321

**Comment by kmiyake** [comment]
参考URL
Rails4 - Railsでモデル名を変更する - Qiita [キータ]
http://qiita.com/ironsand/items/fe1ace0b285c0c576a4a
