### ISSUE TITLE
【最優先でお願いしたいです】github issues, ruffnote issuesとの同期ボタン

### ISSUE THREAD

**Issue by pandeiro245** [timecard/timecard-rails#304]
プロジェクト毎の同期ボタンを押すとそれに関連しているGithub issues, ruffnote issuesを確認し、timecard-railsにないものは取り入れる。

githubとruffnote、どちらとも同期しているプロジェクトであれば、その際にもう片方でもAPI経由でissue追加する

あと、同期ボタンを押した時の処理は毎回API経由で全部のissueを見るのではなく、id descで順次みてtimecard-rails側に保存されている時点で処理を止める。

不明点等、フィードバックお願いします！

なお、実装の際はコードレビューしますのでPRお願いします！

**Comment by kmiyake** [comment]
通常のテーブルに保存されている状態とは違い、シリアライズされたデータの照合作業をどのようにすべきか思案中。

**Comment by kmiyake** [comment]
チケットを作成したユーザー、アサインされたユーザーでtimecard-rails上に存在しないユーザーは仮ユーザーとして自動生成する。

**Comment by kmiyake** [comment]
@pandeiro245 プルリクエストの確認とマージをお願いします。

Feature of Synchronizing with the Github by kmiyake · Pull Request #309 · ruffnote/timecard-rails
https://github.com/ruffnote/timecard-rails/pull/309
