### ISSUE TITLE
作業中リストを表示する

### ISSUE THREAD

**Issue by kmiyake** [timecard/timecard-rails#317]
サイドバーに作業中のユーザーリストを表示する。

**Comment by pandeiro245** [comment]
３カラムになるってことですかー？？

**Comment by kmiyake** [comment]
@pandeiro245 2カラムです。左側のサイドバーに表示させるつもりです。

**Comment by kmiyake** [comment]
@pandeiro245 サイドバーに表示するようにしました。確認してみてください。
