### ISSUE TITLE
基本機能のgem化

### ISSUE THREAD

**Issue by pandeiro245** [timecard/timecard-rails#396]
ラフノートや他のオープンソースで使えるように下記のgemを使うようにしたいです。
https://github.com/ruffnote/acts_as_time_trackable

どこかで一度skypeMTG可能？時間かなり融通ききます

**Comment by kmiyake** [comment]
平日の日本時間16:00以降であれば問題ないです。月曜日か火曜日の16:00でどうしょうか？
