### ISSUE TITLE
home#indexでプロジェクトごとのissueを表示できるようにする

### ISSUE THREAD

**Issue by kmiyake** [timecard/timecard-rails#47]

**Comment by kmiyake** [comment]
home#index部分のBackbone.js化がだいぶ完了。

**Comment by kmiyake** [comment]
start, stopをどう処理するか考える。

**Comment by kmiyake** [comment]
テストを追加。

**Comment by kmiyake** [comment]
start, stopを押したときに作業中ユーザー情報を更新する処理を実装する。

**Comment by kmiyake** [comment]
量が多くなるので一旦commitを整理してPRしよう。

**Comment by kmiyake** [comment]
@pandeiro245 すみません。量が多くなってしまったのですがPRしましたので確認をお願いします。

**Comment by kmiyake** [comment]
To @pandeiro245
heroku環境でどうもうまくいっていないようなのですがログを見ることはできますか？
ローカル環境でproductionモードで動かした際には問題なく動作します。

**Comment by pandeiro245** [comment]
@kmiyake クラウドワークス経由でherokuの情報を教えてもらえれば権限与えます！

**Comment by kmiyake** [comment]
@pandeiro245 メッセージを送りましたので確認お願いします！

**Comment by kmiyake** [comment]
jbuilderでpartialレイアウトに変数を渡せてないみたいだけでなぜだろう。ローカル環境では問題ないんだけどなぁ。

**Comment by kmiyake** [comment]
@pandeiro245 問題かと思われる箇所を修正してPRしましたので確認をお願いします。

Fix not show issue list at home#index by kmiyake · Pull Request #73 · mindia/timecard-rails
https://github.com/mindia/timecard-rails/pull/73/files

**Comment by kmiyake** [comment]
やはりローカルのproduction環境では正常に動く。herokuでの環境との違いはなんだろう。

**Comment by kmiyake** [comment]
@pandeiro245 さらにバグっていると思われる箇所を修正してみました。PRしましたので確認をお願いします。

Get rid of undesirable code that i think by kmiyake · Pull Request #80 · mindia/timecard-rails
https://github.com/mindia/timecard-rails/pull/80

**Comment by kmiyake** [comment]
リソースの取得がうまくいっていない気がする。

**Comment by kmiyake** [comment]
@pandeiro245 すみません。色々とロジックがまずかったようなので、ちょっとテストを書きつつ整理しながら修正します。

**Comment by kmiyake** [comment]
@pandeiro245 PRしましたので確認をお願いします。

Fix AbstractController::DoubleRenderError by kmiyake · Pull Request #82 · mindia/timecard-rails
https://github.com/mindia/timecard-rails/pull/82

**Comment by kmiyake** [comment]
サイト構成を見直す。

**Comment by kmiyake** [comment]
UIを考え直す。

**Comment by kmiyake** [comment]
そもそも他のメンバーの作業時間をリアルタイムで知る必要はあるのか？リアルタイムでコミュニケーションを取りやすくするだけなら作業中なのかどうかだけわかればいいのでは？
