### ISSUE TITLE
github経由で新規登録するとパスワード設定ができない

### ISSUE THREAD

**Issue by pandeiro245** [timecard/timecard-rails#52]
/users/edit
にてCurrent passwordが求められてしまうため。

**Comment by kmiyake** [comment]
@pandeiro245 PRしましたので確認をお願いします。

github経由で新規登録してもパスワードが変更できる by kmiyake · Pull Request #56 · mindia/timecard-rails
https://github.com/mindia/timecard-rails/pull/56
