### ISSUE TITLE
チケットをgithubへ登録するか、timecardへ登録するかによってassigneeのリストを切り替える

### ISSUE THREAD

**Issue by kmiyake** [timecard/timecard-rails#97]
assigneeのリスト表示を以下のようにする。
1. github連携なしのプロジェクト
   すべてのプロジェクトメンバーを表示
2. github連携ありのプロジェクト
   2-1. Add Github Issueを選択
   githubでcollaboratorに登録されているユーザーのみ表示

2-2. Add Github Issueを未選択
すべてのプロジェクトメンバーを表示

**Comment by pandeiro245** [comment]
ruffnoteもお願いしますｗ

**Comment by kmiyake** [comment]
@pandeiro245 Githubの機能が安定したら取り掛かります！
